// Placeholder listings — replace with SheetDB API call when ready.
// Each object matches the Google Sheets column structure exactly.
const PLACEHOLDER_LISTINGS = [
  {
    id: 'EXC-001',
    category: 'excavator',
    brand: 'Hyundai',
    model: 'R210-9S',
    year: 2018,
    hours: 7200,
    condition: '양호 (Good)',
    compatible_models: '',
    price_krw: 42000000,
    location_kr: '경남 창원',
    photos: 'https://picsum.photos/seed/exc001a/800/600,https://picsum.photos/seed/exc001b/800/600,https://picsum.photos/seed/exc001c/800/600',
    status: 'available',
    name_kr: '현대 R210-9S 굴착기',
    name_uz: 'Hyundai R210-9S ekskavatori',
    name_ru: 'Экскаватор Hyundai R210-9S',
    name_en: 'Hyundai R210-9S Excavator',
    desc_kr: '상태 양호한 현대 R210-9S 굴착기입니다. 정기 점검 완료. 경남 창원에 위치해 있으며 즉시 출하 가능합니다.',
    desc_uz: "Hyundai R210-9S ekskavatori yaxshi holatda. Muntazam texnik ko'rik o'tkazilgan. Changwon shahrida joylashgan, darhol jo'natishga tayyor.",
    desc_ru: 'Экскаватор Hyundai R210-9S в хорошем состоянии. Регулярное ТО пройдено. Находится в г. Чхансон, провинция Кённам. Готов к отгрузке.',
    desc_en: 'Hyundai R210-9S excavator in good condition. Regular maintenance completed. Located in Changwon, Gyeongnam. Ready for shipment.'
  },
  {
    id: 'EXC-002',
    category: 'excavator',
    brand: 'Doosan',
    model: 'DX300LC-5',
    year: 2016,
    hours: 11500,
    condition: '수리 필요 (Needs repair)',
    compatible_models: '',
    price_krw: 28000000,
    location_kr: '경기 용인',
    photos: 'https://picsum.photos/seed/exc002a/800/600,https://picsum.photos/seed/exc002b/800/600',
    status: 'available',
    name_kr: '두산 DX300LC-5 굴착기',
    name_uz: 'Doosan DX300LC-5 ekskavatori',
    name_ru: 'Экскаватор Doosan DX300LC-5',
    name_en: 'Doosan DX300LC-5 Excavator',
    desc_kr: '두산 대형 굴착기. 일부 수리 필요하나 가격에 반영됨. 협의 가능.',
    desc_uz: "Doosan yirik ekskavatori. Ba'zi ta'mirlash ishlari talab etiladi, ammo narxga kiritilgan. Narx muzokarali.",
    desc_ru: 'Большой экскаватор Doosan. Требует частичного ремонта — учтено в цене. Цена договорная.',
    desc_en: 'Large Doosan excavator. Requires partial repair — reflected in the price. Price negotiable.'
  },
  {
    id: 'EXC-003',
    category: 'excavator',
    brand: 'Komatsu',
    model: 'PC200-8',
    year: 2019,
    hours: 5100,
    condition: '최상 (Excellent)',
    compatible_models: '',
    price_krw: 55000000,
    location_kr: '인천',
    photos: 'https://picsum.photos/seed/exc003a/800/600,https://picsum.photos/seed/exc003b/800/600,https://picsum.photos/seed/exc003c/800/600',
    status: 'reserved',
    name_kr: '코마츠 PC200-8 굴착기',
    name_uz: 'Komatsu PC200-8 ekskavatori',
    name_ru: 'Экскаватор Komatsu PC200-8',
    name_en: 'Komatsu PC200-8 Excavator',
    desc_kr: '최상 상태의 코마츠 굴착기. 5,100시간 사용. 인천항 근처 위치. 수출 서류 준비 가능.',
    desc_uz: "A'lo holatdagi Komatsu ekskavatori. 5,100 soat ishlagan. Incheon portiga yaqin joylashgan. Eksport hujjatlari tayyorlanishi mumkin.",
    desc_ru: 'Экскаватор Komatsu в отличном состоянии. 5 100 моточасов. Находится рядом с портом Инчхон. Экспортные документы подготавливаются.',
    desc_en: 'Komatsu excavator in excellent condition. 5,100 hours. Located near Incheon port. Export documents can be prepared.'
  },
  {
    id: 'PRT-001',
    category: 'parts',
    brand: 'Hyundai',
    model: 'Гидронасос / Hydraulic Pump',
    year: null,
    hours: null,
    condition: '재생품 (Reconditioned)',
    compatible_models: 'R180-7, R210-7, R210-9, R200-7',
    price_krw: 3500000,
    location_kr: '부산',
    photos: 'https://picsum.photos/seed/prt001a/800/600,https://picsum.photos/seed/prt001b/800/600',
    status: 'available',
    name_kr: '현대 R210 시리즈 유압펌프',
    name_uz: 'Hyundai R210 seriyasi gidronasosi',
    name_ru: 'Гидронасос Hyundai серия R210',
    name_en: 'Hyundai Hydraulic Pump — R210 Series',
    desc_kr: '현대 R180/R210 시리즈 호환 재생 유압펌프. 전문 업체에서 테스트 완료. 부산에서 발송 가능.',
    desc_uz: "Hyundai R180/R210 seriyasiga mos keluvchi qayta tiklangan gidronasos. Mutaxassis tomonidan sinovdan o'tkazilgan. Busandan jo'natish mumkin.",
    desc_ru: 'Восстановленный гидронасос для Hyundai R180/R210. Тест проведён в специализированном сервисе. Отправка из Пусана.',
    desc_en: 'Reconditioned hydraulic pump for Hyundai R180/R210 series. Professionally tested. Ships from Busan.'
  },
  {
    id: 'PRT-002',
    category: 'parts',
    brand: 'Doosan',
    model: 'Гусеничные башмаки / Track Shoes',
    year: null,
    hours: null,
    condition: '신품 (New)',
    compatible_models: 'DX180LC, DX225LC, DX300LC',
    price_krw: 1800000,
    location_kr: '경남 창원',
    photos: 'https://picsum.photos/seed/prt002a/800/600',
    status: 'available',
    name_kr: '두산 트랙 슈 세트 (DX180–300)',
    name_uz: "Doosan traktor zanjiri to'plami (DX180–300)",
    name_ru: 'Гусеничные башмаки Doosan DX180–300 (комплект)',
    name_en: 'Doosan Track Shoe Set — DX180–300',
    desc_kr: '두산 DX 시리즈용 신품 트랙 슈 세트. 수량 한정. 문의 시 재고 확인.',
    desc_uz: "Doosan DX seriyasi uchun yangi traktor zanjiri to'plami. Miqdori cheklangan. Murojaat vaqtida mavjudligini tekshiring.",
    desc_ru: 'Новые гусеничные башмаки для Doosan серии DX. Ограниченное количество. При обращении уточняйте наличие.',
    desc_en: 'New track shoe set for Doosan DX series. Limited stock. Confirm availability upon inquiry.'
  },
  {
    id: 'OTH-001',
    category: 'other_machinery',
    brand: 'Volvo',
    model: 'L90H',
    year: 2017,
    hours: 8900,
    condition: '양호 (Good)',
    compatible_models: '',
    price_krw: 65000000,
    location_kr: '경북 포항',
    photos: 'https://picsum.photos/seed/oth001a/800/600,https://picsum.photos/seed/oth001b/800/600',
    status: 'sold',
    name_kr: '볼보 L90H 휠 로더',
    name_uz: "Volvo L90H g'ildirakli yuklagich",
    name_ru: 'Колёсный погрузчик Volvo L90H',
    name_en: 'Volvo L90H Wheel Loader',
    desc_kr: '볼보 L90H 휠 로더. 상태 양호. 경북 포항 위치.',
    desc_uz: "Volvo L90H g'ildirakli yuklagich. Yaxshi holat. Pohang, Gyeongbuk joylashgan.",
    desc_ru: 'Колёсный погрузчик Volvo L90H. Хорошее состояние. Г. Пхохан, провинция Кёнбук.',
    desc_en: 'Volvo L90H wheel loader. Good condition. Located in Pohang, Gyeongbuk.'
  }
];
